services:
  react-moigioi:
    container_name: react-moigioi
    image: react-moigioi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    # ports:
    #   - 9000:9000
    command: yarn dev --host
    networks:
      - test-net # Liên kết với mạng đã tồn tại


# networks:
#   aloper-prod_default: # Sử dụng mạng external
#     external: true

networks:
  test-net:
    external: true