version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: FE-Clinet-image # Đặt tên cho image ở đây
    container_name: FE-Clinet-image-container # Đặt tên cho container ở đây
    ports:
      - "80:82"
    volumes:
      - .:/app
      - /app/node_modules
