services:
  react-app:
    container_name: REACTCLIENT
    build:
      context: .
      dockerfile: Dockerfile
    image: fe-client-image # Đặt tên cho image
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - aloper-prod_default # Liên kết với mạng đã tồn tại

networks:
  aloper-prod_default: # Sử dụng mạng external
    external: true
